### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by elaur** [Yhonay/antipopads#1]
Hello,

How do you extract the list for this one ?
beacause I'm looking as well to extract the list of all domain registered by this registrar http://www.tastereports.com/registrar.html?registrar_id=1622
it is registering just fake domains with redirect for ads, and I want to ban all his domains. If you are looking over domains registered you will see most of them are the same.

**Comment by Veticia** [comment]
I just crawl a few websites that I know use popads.net and check what domain their script loaded from. If it's new, I add it to the list of known domains.
