### ISSUE TITLE
[Info] hosts file was added to hosts.extras project

### ISSUE THREAD

**Issue by FadeMind** [Yhonay/antipopads#11]
Hello @Yhonay I added your hosts file to project [hosts.extras](https://github.com/FadeMind/hosts.extras/), part of [Steven Black's Hosts Project](https://github.com/StevenBlack/hosts) project.

Commit: https://github.com/FadeMind/hosts.extras/commit/6ad79e7e2de999bea0eb26bf9bf69115e074c1d2

Regards, Thanks for antipopads hosts file.

FadeMind

CC @StevenBlack @funilrys

**Comment by funilrys** [comment]
Looks good to me :)
