### ISSUE TITLE
hostsman

### ISSUE THREAD

**Issue by adzkii-i** [Yhonay/antipopads#12]
hostsman don't work with rawgithub, is there any alternative link to grab the hosts file?

cheers

**Comment by Veticia** [comment]
Try this:
https://cdn.polfurs.org/antipopads/hosts

It is however behind an extensive list of ip blocklist and a cloudflare so if it doesn't work for you then I'm out of options. None of the free github compatible proxies I've tried worked, and I don't have any more servers I can borrow.
