### ISSUE TITLE
ublock origin nie obsługuje jednostek godzinowych

### ISSUE THREAD

**Issue by ghost** [Yhonay/antipopads#15]
![2018-07-20-antipopads_popads txt at master yhonay_antipopads](https://user-images.githubusercontent.com/5884000/43018953-9f78a610-8c5b-11e8-954f-83bd6d631885.png)

**Comment by Veticia** [comment]
Fixed by commit 485978bfcf7d0e79abbd66101bb3c0d04e17b06d
