### ISSUE TITLE
adblock plus nie wspiera pełnego blokowania stron

### ISSUE THREAD

**Issue by ghost** [Yhonay/antipopads#16]
![2018-07-20-antipopads_popads txt at master yhonay_antipopads](https://user-images.githubusercontent.com/5884000/43019145-3aaee4d2-8c5c-11e8-80a1-b5a43b7cbb3f.png)

można usunąć przedrostek
```
[Adblock Plus 2.0]
```

**Comment by Veticia** [comment]
Nie wiem za bardzo co tu jest problemem, ale skoro pull request #19 miał to naprawiać a wszystko z tego requesta już jest w 485978bfcf7d0e79abbd66101bb3c0d04e17b06d to uznaję za naprawione.
