### ISSUE TITLE
AdGuard can't identify FIRST LINE

### ISSUE THREAD

**Issue by bestpika** [Yhonay/antipopads#26]
Hello, this list's first line at AdGuard can't be identified.
![image](https://user-images.githubusercontent.com/5698157/49277723-9c1de000-f4bd-11e8-897b-489066db3509.png)
The correct value is `[Adblock Plus]`.
Thank you.

**Comment by Veticia** [comment]
fixed by d9e66448d1b52f9c6993086655c45926d0fc4a93
