### ISSUE TITLE
Can't subscribe to list with AdGuard browser ext

### ISSUE THREAD

**Issue by Yunogamer** [Yhonay/antipopads#29]
AdGuard says:

Error
Error while adding your custom filter

and thats it. Adding manually doesnt work either.. yet i can add any other random lists fine..

**Comment by superlex** [comment]
@Yunogamer 

Try
- disable English (Base) filter
- add the list
- re-enable English (Base) filter

**Comment by superlex** [comment]
maximtop (AdGuard dev) suggests:

> Temporarily you can add the unblocking rule for this request
> `@@||raw.githubusercontent.com/Yhonay/antipopads/master/popads.txt`

They will fix with v 3.3.

**Comment by Yunogamer** [comment]
That worked thanks.
