### ISSUE TITLE
Not compare AdBlock Plus

### ISSUE THREAD

**Issue by S8D** [Yhonay/antipopads#3]
Please add these line to your filter,
[Adblock Plus 2.0]
! Version: 2017.xx.xx
! Title: xxx
! Expires: 1 days
! Homepage: xxx
! Licence: xxx
! ChangeLog: ...

**Comment by Veticia** [comment]
Missing headers added, however I'd like to keep it at 1 hour expire (unless that's not compatible with adblock plus) as the domains can update frequently and 1 day old list can be useless.

Please test.

**Comment by S8D** [comment]
Thanks Yhonay.
I want to block PodAds by IP on Chrome
PodAds 's domains connect to 107.170.2.22
