### ISSUE TITLE
List of 19625 websites using PopAds

### ISSUE THREAD

**Issue by anonsubmitter** [Yhonay/antipopads#4]
Here is a list of 19625 websites using PopAds, in case you have any use of it: https://publicwww.com/websites/PopAds.net+Popunder+Code/

**Comment by Veticia** [comment]
Thank you. I was looking for something like this.

After running some tests and crawling a short list of 2340 websites I've found 402 unique domains, all of which were already in my list.

Link you've provided will help me update my list more frequently and with smaller delay as new domains are added by popads.
